[Sample]
# sample length in mm
l = 12.68
l_err = 0.01e-3
# sample diameter in mm
dia = 18.83
dia_err = 0.01

[Storage]
# downstream storage mode: Dv or bd
# Dv mode calculates bd = Dv x fluid compressibility for each measurement
# bd mode uses a directly measured downstream storage capacity
mode = Dv
# downstream volume in m^3
Dv = 9.6085e-6
# error in downstream volume
Dv_err = 0.01e-6

[Experiment]
Temp = 293
# 'water' ,'argon' or 'rheolube'
permeant = water

[File]
# data file type: dat or mat
mode = dat
# Number of header rows
HeaderRows = 3
# time column
time_col = 0
# upstream Pressure column
Pup_col = 1
# downstream pressure column
Pdwn_col = 2
# Confining pressure column
Pc_col = 3

[Processing]
# processing type: sin for one selected oscillation interval, cont for continuous moving-window processing
proc_type = sin

[Fitting]
# No of remaples for bootstrapping
N = 20
# weight 0.5 equal wiegth of A and phi
w = 0.5
#min period s
Tmin = 10
#max period s
Tmax = 10000
